apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-hello-world-1
  namespace: demo1
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
        - path: /hello-world-1
          pathType: Prefix
          backend:
            service:
              name: test
              port:
                number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-hello-world-2
  namespace: demo2
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
        - path: /hello-world-1
          pathType: Prefix
          backend:
            service:
              name: test
              port:
                number: 80
